# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeeditem',
            name='message',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
