# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditem_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
